### PR TITLE
ALP-98 Fixed POST /volunteers 

### LINKED ISSUE #98: Fix volunteer post endpoint to work with updated schema

### PR DESCRIPTION
**Pull request by thaingocnguyen**

### CODE REVIEW

File: aunt-leahs-functions/volunteers/index.js [hunk 1]
```diff
@@ -94,21 +110,35 @@ module.exports = function (context, req) {
...
+        var emergencyContactId = null;
+
+        request.on('row', function (columns) {
+            context.log('New id: %d', columns[0].value);
+            emergencyContactId = columns[0].value;
+        });
+
+        request.on('requestCompleted', function () {
+            postVolunteers(emergencyContactId);
+        });
```
Comment (michaelfromyeg) [inline aunt-leahs-functions/volunteers/index.js:127]: Should there be some sort of catch in case the emergency contact ID is null here? In the off chance there is some error establishing the connection

**Review by michaelfromyeg — APPROVED** [review]
One minor comment, overall looks really good. Some other edits will be merged in as well after the PUT PR is added

File: aunt-leahs-functions/volunteers/index.js [hunk 2]
```diff
@@ -29,58 +30,73 @@ module.exports = function (context, req) {
...
 
         // Should be refactored to use JSON destructing, I think
         const firstName = formInput.firstName;
         const lastName = formInput.lastName;
         const email = formInput.email;
+        const phone = formInput.phone;
         const streetAddress = formInput.streetAddress;
         const postalCode = formInput.postalCode;
         const mailingList = formInput.mailingList;
-        const contactEmail = formInput.contactEmail;
```
Comment (codygagnon) [inline aunt-leahs-functions/volunteers/index.js]: This should be rewritten to use destructuring.

**Comment by thaingocnguyen** [comment]
Resolved code review comments

**Review by codygagnon — APPROVED** [review]
